# Generated by Django 4.1.7 on 2023-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlisting_bid_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image",
            field=models.URLField(),
        ),
    ]
