# Generated by Django 4.1.7 on 2023-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlisting_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
