# Generated by Django 4.1.7 on 2023-04-20 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auctionlisting_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="max_bid",
        ),
    ]
