# Generated by Django 4.1.7 on 2023-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_bid_bid_bid_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="amount",
            field=models.FloatField(default=0, max_length=64),
        ),
    ]
