# Generated by Django 4.1.7 on 2023-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_bid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="max_bid",
            field=models.FloatField(blank=True, default=0, max_length=64),
        ),
    ]
