# Generated by Django 4.1.7 on 2023-04-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_auctionlisting_max_bid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watching",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watching",
                        to="auctions.auctionlisting",
                    ),
                ),
                (
                    "watch_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_by",
                        to="auctions.auctionlisting",
                    ),
                ),
            ],
        ),
    ]
