# Generated by Django 4.1.7 on 2023-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_watching"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watching",
            new_name="Watchlist",
        ),
    ]
