# Generated by Django 4.1.7 on 2023-04-21 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_watchlist_watch_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watch_listing",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watching",
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="watch_user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watched_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
