# Generated by Django 4.1.7 on 2023-04-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_watchlist_watch_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="watch_listing",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="watch_user",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(default=0, to="auctions.auctionlisting"),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
