# Generated by Django 4.1.7 on 2023-04-21 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0014_remove_watchlist_listing_watchlist_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bid",
        ),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
