# Generated by Django 4.1.7 on 2023-04-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_remove_bid_bid_bid_listing_bid_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watched",
                to="auctions.auctionlisting",
            ),
        ),
    ]
