# Generated by Django 4.1.7 on 2023-04-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_alter_bid_listing_alter_watchlist_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
    ]
