# Generated by Django 4.1.7 on 2023-04-22 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_watchlist_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userwatch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
