# Generated by Django 4.1.7 on 2023-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_auctionlisting_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
