# Generated by Django 4.1.7 on 2023-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
