# Generated by Django 4.1.7 on 2023-04-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0024_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
